<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Text Aventure</title>
</head>
<body>
    <main>
        <div class="console-box">
            <?php foreach($arrayAssociativo->messages as $message): ?>
                <p><?= $message ?></p>
            <?php endforeach ?>
            <div>
                <form>
                    <input type="text" name="command"> 
                    <input type="submit">
                </form>
            </div>
        </div>
    </main>
</body>
</html>